export const NAV_ITEMS = [
  {
    id: "rides",
    to: "/rides",
    label: "Claim Rides",
    icon: "DirectionsCar",
    rolesVisible: ["admin", "driver"],
    iconColor: (t) => t.palette.primary.main,
  },
  {
    id: "clock",
    to: "/clock",
    label: "Time Clock",
    icon: "AccessTime",
    rolesVisible: ["admin", "driver"],
    iconColor: (t) => t.palette.info.main,
  },
  {
    id: "info",
    to: "/info",
    label: "Drop-Off Info",
    icon: "Info",
    rolesVisible: ["admin", "driver"],
    iconColor: (t) => t.palette.info.main,
  },
  {
    id: "important-info",
    to: "/important",
    label: "Important Information",
    icon: "PriorityHigh",
    rolesVisible: ["admin", "driver"],
    iconColor: (t) => t.palette.error.main,
  },
  {
    id: "notes",
    to: "/notes",
    label: "Quote Notes",
    icon: "Notes",
    rolesVisible: ["admin"],
    iconColor: (t) => t.palette.secondary.main,
  },
  {
    id: "drop-guides",
    to: "/drop-guides",
    label: "Vehicle Tips",
    icon: "CarRepair",
    rolesVisible: ["admin", "driver"],
    iconColor: (t) => t.palette.warning.main,
    hidden: true,
  },
  {
    id: "directory",
    to: "/directory",
    label: "Directory & Escalations",
    icon: "ContactEmergency",
    rolesVisible: ["admin", "driver", "shootout"],
    iconColor: (t) => t.palette.error.main,
  },
  {
    id: "calendar",
    to: "/calendar",
    label: "Calendar & Availability",
    icon: "CalendarMonth",
    rolesVisible: ["admin", "driver"],
    iconColor: (t) => t.palette.success.main,
  },
  {
    id: "games",
    to: "/games",
    label: "Games",
    icon: "SportsEsports",
    rolesVisible: ["admin", "driver", "shootout", "guest"],
    iconColor: (t) => t.palette.warning.main,
  },
  {
    id: "tickets",
    to: "/tickets",
    label: "Support Tickets",
    icon: "ConfirmationNumber",
    rolesVisible: ["admin", "driver"],
    iconColor: (t) => t.palette.info.main,
  },
  {
    id: "shuttle-tickets",
    to: "/tickets/legacy",
    label: "Shuttle Tickets",
    icon: "AirportShuttle",
    rolesVisible: ["admin", "driver"],
    iconColor: (t) => t.palette.warning.main,
  },
  {
    id: "admin-time-log",
    to: "/admin-time-log",
    label: "Admin Logs",
    icon: "TableChart",
    rolesVisible: ["admin"],
    iconColor: (t) => t.palette.primary.main,
  },
  {
    id: "admin-user-manager",
    to: "/admin-user-manager",
    label: "User Manager",
    icon: "ManageAccounts",
    rolesVisible: ["admin"],
    iconColor: (t) => t.palette.info.main,
  },
  {
    id: "admin-notifications",
    to: "/admin/notifications",
    label: "Notifications",
    icon: "Notifications",
    rolesVisible: ["admin"],
    iconColor: (t) => t.palette.info.main,
  },
  {
    id: "ride-entry",
    to: "/ride-entry",
    label: "Add Ride",
    icon: "AddCircle",
    rolesVisible: ["admin"],
    iconColor: (t) => t.palette.success.main,
  },
  {
    id: "chatbot-settings",
    to: "/admin/chatbot-settings",
    label: "Chat Bot",
    icon: "SmartToy",
    rolesVisible: ["admin"],
    iconColor: (t) => t.palette.success.main,
  },
  {
    id: "shop-manager",
    to: "/shop-manager",
    label: "Shop Manager",
    icon: "ShoppingCart",
    rolesVisible: ["admin"],
    iconColor: (t) => t.palette.success.main,
  },
  {
    id: "gift-card-manager",
    to: "/gift-card-manager",
    label: "Gift Cards",
    icon: "CardGiftcard",
    rolesVisible: ["admin"],
    iconColor: (t) => t.palette.warning.main,
  },
];
